@startuml
skinparam roundcorner 15
skinparam linetype ortho
skinparam shadowing false
skinparam class {
    BackgroundColor white
    BorderColor black
    ArrowColor black
}

hide circle
hide empty members

entity "H" as H

entity "I" as I {
    # I_ID
}

H ||.. I : "is a  "

@enduml